const resources = {
    tamil: {
        translation: {
            "WebsiteHeader": "திருக்குறள்",
            "TagLine": "உலகப் பொது மறை",
            "Kural": "குறள்",
            "MuVaExplanation": "மு.வ உரை",
            "SolomonPaapaiyaExplanation": "சாலமன் பாப்பையா உரை",
            "KalaignarExplanation": "கலைஞர் உரை",
            "Couplet": "ஆங்கிலம்",
            "EnglishExplanation": "ஆங்கில விளக்கம்",
            "Transliteration": "எழுத்துப் பெயர்ப்பு",
            "Kurals": "குறள்கள்",
            "Chapters": "அதிகாரங்கள்",
            "Sections": "பால்கள்",
            "ChapterGroups": "இயல்கள்",
            "Search": "தேடல்",
            "Language": "English/ஆங்கிலம்",
            "Chapter": "அதிகாரம்",
            "ChapterInTamil": "அதிகாரம்",
            "ChapterGroup": "இயல்",
            "ChapterGroupInTamil": "இயல்",
            "ChapterTransliteration": "Adhigaaram",
            "ChapterGroupTransliteration": "Iyal",
            "Section": "பால்",
            "SectionInTamil": "பால்",
            "SectionTransliteration": "Paal",
            "StartsWith": "தொடங்கும் குறள்",
            "EndsWith": "முடியும் குறள்",
            "Contains": "உள்ள குறள்",
            "SearchButtonText": "தேடு",
            "SearchPlaceholder": "நட்பு உள்ள குறள் தேட, Natpu டைப் செய்து ஸ்பேஸ்பார் அழுத்துங்கள்",
            "NoRecords": "0 குறள்"
        }
    },
    english: {
        translation: {
            "WebsiteHeader": "Thirukkural",
            "TagLine": "Ulagap Podhu Marai",
            "Kural": "Kural",
            "MuVaExplanation": "Mu. Varadharasanar's Explanation",
            "SolomonPaapaiyaExplanation": "Solomon Paapaiya's Explanation",
            "KalaignarExplanation": "Kalaignar's Explanation",
            "Couplet": "Couplet",
            "EnglishExplanation": "English Explanation",
            "Transliteration": "Transliteration",
            "Kurals": "Kurals",
            "Chapters": "Chapters",
            "Sections": "Sections",
            "ChapterGroups": "Chapter Groups",
            "Search": "Search",
            "Language": "தமிழ்/Tamil",
            "Chapter": "Chapter",
            "ChapterInTamil": "அதிகாரம்",
            "ChapterGroup": "Chapter Group",
            "ChapterGroupInTamil": "இயல்",
            "ChapterTransliteration": "Adhigaaram",
            "ChapterGroupTransliteration": "Iyal",
            "Section": "Section",
            "SectionInTamil": "பால்",
            "SectionTransliteration": "Paal",
            "StartsWith": "StartsWith",
            "EndsWith": "EndsWith",
            "Contains": "Contains",
            "SearchButtonText": "Search",
            "SearchPlaceholder": "Search",
            "NoRecords": "0 Kural"
        }
    }
}

export default resources;